In [1]:
import numpy as np
import pandas as pd
from scipy import io
import matplotlib.pyplot as plt
from network import network

In [2]:
# 加载神经网络权重
weight = io.loadmat('/home/sjl/桌面/machine learning/mlclass-ex3-005/mlclass-ex3/ex3weights.mat')
weight = [weight['Theta1'], weight['Theta2']]
weight

[array([[-2.25623899e-02, -1.05624163e-08,  2.19414684e-09, ...,
         -1.30529929e-05, -5.04175101e-06,  2.80464449e-09],
        [-9.83811294e-02,  7.66168682e-09, -9.75873689e-09, ...,
         -5.60134007e-05,  2.00940969e-07,  3.54422854e-09],
        [ 1.16156052e-01, -8.77654466e-09,  8.16037764e-09, ...,
         -1.20951657e-04, -2.33669661e-06, -7.50668099e-09],
        ...,
        [-1.83220638e-01, -8.89272060e-09, -9.81968100e-09, ...,
          2.35311186e-05, -3.25484493e-06,  9.02499060e-09],
        [-7.02096331e-01,  3.05178374e-10,  2.56061008e-09, ...,
         -8.61759744e-04,  9.43449909e-05,  3.83761998e-09],
        [-3.50933229e-01,  8.85876862e-09, -6.57515140e-10, ...,
         -1.80365926e-06, -8.14464807e-06,  8.79454531e-09]]),
 array([[-0.76100352, -1.21244498, -0.10187131, -2.36850085, -1.05778129,
         -2.20823629,  0.56383834,  1.21105294,  2.21030997,  0.44456156,
         -1.18244872,  1.04289112, -1.60558756,  1.30419943,  1.37175046,
       

In [8]:
# 加载特征值和目标向量
data = io.loadmat('/home/sjl/桌面/machine learning/mlclass-ex3-005/mlclass-ex3/ex3data1.mat')
x = data['X'] # 特征值
y = data['y'] # 目标向量
# 对y做预处理
m, n = x.shape
y[y==10] = 0
y1 = np.zeros((m, 10))
for i in range(10):
    y1[:, i] = np.int32(y==i).reshape(1, -1)
y = y1
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [6]:
# 实例化神经网络类
net = network([400, 25, 10], x, y)
predict_y = net.feedforward(weight)
predict_y

array([[0.13749181, 0.12674176, 0.17011121, ..., 0.09815053, 0.11218706,
        0.21526563],
       [0.15595354, 0.15158434, 0.11469629, ..., 0.08180693, 0.14332138,
        0.21208219],
       [0.12439528, 0.09736958, 0.15147863, ..., 0.18637789, 0.18152735,
        0.14896324],
       ...,
       [0.19297595, 0.14985151, 0.15551025, ..., 0.02957904, 0.08104372,
        0.04847032],
       [0.12830654, 0.13576931, 0.16814949, ..., 0.09267986, 0.18331129,
        0.2251713 ],
       [0.1612844 , 0.07446977, 0.19527661, ..., 0.15962248, 0.06635092,
        0.17053065]])